version: "3.11"

services:
  web:
    image: web:0.1
    deploy:
      mode: replicated
      replicas: 10
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8888:80"
    networks:
      - web

networks:
  web:
    external:
      name: web